implemented
AlexanderSharygin/java-explore-with-me-correct pull request #1
Opened 2023-02-25 09:52 UTC by AlexanderSharygin

2023-02-26 05:31 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-02-26 05:31 UTC, FanaticFiz commented on stats-service/src/main/java/ru/practicum/ewm/stats/Main.java
> +package ru.practicum.ewm.stats;
Остался у тебя какой то огрызок - надо удалить...

2023-02-26 05:31 UTC, FanaticFiz commented on stats-service/pom.xml
> +        <maven.compiler.source>11</maven.compiler.source>
Эти свойства можно было бы указать один раз в родительской `pom` файле.

2023-02-26 05:31 UTC, FanaticFiz commented on stats-service/stats-client/src/main/java/ru/practicum/ewm/cient/BaseClient.java
> +    private <T> ResponseEntity<Object> makeAndSendRequest(HttpMethod method, String path, Long userId, @Nullable Map<String, Object> parameters, @Nullable T body) {
- Строка не должна переваливать за 120 символов.
- Параметр `Long userId` не используется!

2023-02-26 05:31 UTC, FanaticFiz commented on stats-service/stats-server/src/main/java/ru/practicum/ewm/service/StatsService.java
> +        return HitMapper.toHitDto(hitRepository.save(hit));
`hitRepository.save(hit)`
Это главное действие в этом методе. Не прячь его где-то в строке другого кода, оно достойно отдельной строки! Это действие первично, всё остальное вторично!

2023-02-26 05:31 UTC, FanaticFiz commented on stats-service/stats-server/src/main/resources/application.yml
> +    #driverClassName: org.postgresql.Driver
удалить мусор

2023-02-26 05:31 UTC, FanaticFiz commented on stats-service/stats-server/src/main/resources/schema.sql
> +drop table if exists hit;
Этому файлу тоже не помешает выравнивание

```
create table if not exists hit
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id    INTEGER REFERENCES APP (id) ON DELETE CASCADE,
    uri       VARCHAR(200) NOT NULL,
    ip        VARCHAR(64)  NOT NULL,
    date_time TIMESTAMP WITHOUT TIME ZONE
);
```

2023-02-27 19:02 UTC, AlexanderSharygin commented on stats-service/src/main/java/ru/practicum/ewm/stats/Main.java
> +package ru.practicum.ewm.stats;
fixed

2023-02-27 19:03 UTC, AlexanderSharygin commented on stats-service/pom.xml
> +        <maven.compiler.source>11</maven.compiler.source>
fixed

2023-02-27 19:05 UTC, AlexanderSharygin commented on stats-service/stats-client/src/main/java/ru/practicum/ewm/cient/BaseClient.java
> +    private <T> ResponseEntity<Object> makeAndSendRequest(HttpMethod method, String path, Long userId, @Nullable Map<String, Object> parameters, @Nullable T body) {
fixed

2023-02-27 19:07 UTC, AlexanderSharygin commented on stats-service/stats-server/src/main/java/ru/practicum/ewm/service/StatsService.java
> +        return HitMapper.toHitDto(hitRepository.save(hit));
fixed

2023-02-27 19:07 UTC, AlexanderSharygin commented on stats-service/stats-server/src/main/resources/application.yml
> +    #driverClassName: org.postgresql.Driver
fixed

2023-02-27 19:14 UTC, AlexanderSharygin commented on stats-service/stats-server/src/main/resources/schema.sql
> +drop table if exists hit;
fixed

2023-02-27 19:16 UTC, AlexanderSharygin commented
Спасибо, с докером вроде все в порядке. Были некоторые проблемы — но разобрался и получил новый опыт :)

2023-02-28 18:40 UTC, FanaticFiz approved these changes

2023-03-01 19:14 UTC, merged