Main svc
AlexanderSharygin/java-explore-with-me-correct pull request #2
Opened 2023-03-09 19:53 UTC by AlexanderSharygin

2023-03-10 20:28 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-03-10 20:28 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/main_service/EwmMainService.java
> +@SpringBootApplication(scanBasePackages = {"ru.practicum.ewm.client",
А зачем тебе понадобилось всё это прописывать и указывать соседний проект? 
`ru.practicum.ewm.client`

Он же подключен как зависимость...

Точно нельзя просто оставить `@SpringBootApplication` ?

2023-03-10 20:28 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/main_service/compilation/service/CompilationService.java
> +        List<ParticipationRequest> requests = requestRepository
Строки с 164-175 тут...
дублируются с приватным методом getConfirmedRequestsCountForEvents в EventService

2023-03-10 20:28 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/main_service/compilation/service/CompilationService.java
> +        ResponseEntity<Object> response = statClient.getStats("2000-01-01 00:00:00",
response нигде не используется...

2023-03-10 20:28 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/main_service/location/service/LocationService.java
> +    public Location save(Location location) {
Давай на этом примере покажу как можно лучше структурировать код.

```
    public Location save(Location location) {
        Optional<Location> existedLocation = locationRepository.findByLatAndLon(location.getLat(), location.getLon());
        if (existedLocation.isEmpty()) {
            locationRepository.save(location);
        }
        
        return locationRepository
                .findByLatAndLon(location.getLat(), location.getLon())
                .orElse(null);
    }
```

- не переносим findByLatAndLon на новую строку - влазит в 120 символов
- перед return отступ - визуально отделяем
- и вот в конце уже цепочку из нескольких методов нарочно переносим каждое действие на новую строку. Хотя они и влазят в 120 но действий несколько, а не одно.
- ну и нельзя конечно оставлять .orElse(null); - тебе нужно решить что делать. null возвращать нельзя!

2023-03-10 20:28 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/main_service/event/util/SortFullDtoByViewsComparator.java
> +public class SortFullDtoByViewsComparator implements Comparator<EventFullDto> {
не используется, как и соседний...

2023-03-10 20:28 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/main_service/location/dto/LocationDto.java
> +public class LocationDto {
класс не используется?

2023-03-10 20:28 UTC, FanaticFiz commented on main-service/src/main/resources/schema.sql
> +    id
Что за прикол с форматированием? Почему каждое слово но отдельной строке? ))

2023-03-10 20:28 UTC, FanaticFiz commented on stats-service/stats-server/src/main/resources/application.yml
> +    #driverClassName: org.postgresql.Driver
Подчищай же...

2023-03-11 11:36 UTC, AlexanderSharygin commented on main-service/src/main/java/ru/practicum/ewm/main_service/EwmMainService.java
> +@SpringBootApplication(scanBasePackages = {"ru.practicum.ewm.client",
Понадобилось все это пописать так как main сервис упорно не хотел видеть соседний проект. Без этого, к сожалению, падает ошибка - что-то вроде не вижу StatService bean

2023-03-11 11:39 UTC, AlexanderSharygin commented on stats-service/stats-server/src/main/resources/application.yml
> +    #driverClassName: org.postgresql.Driver
Ах, сори все время собираюсь это удалить после раскатки в докер... И каждый аз забываю( fixed

2023-03-11 11:57 UTC, AlexanderSharygin commented on main-service/src/main/resources/schema.sql
> +    id
ХМ... Странно... Такого я точно сделать не мог) видимо не уследил за автоформатером? Fixed

2023-03-11 11:58 UTC, AlexanderSharygin commented on main-service/src/main/java/ru/practicum/ewm/main_service/location/dto/LocationDto.java
> +public class LocationDto {
Fixed

2023-03-11 11:59 UTC, AlexanderSharygin commented on main-service/src/main/java/ru/practicum/ewm/main_service/event/util/SortFullDtoByViewsComparator.java
> +public class SortFullDtoByViewsComparator implements Comparator<EventFullDto> {
уже даже не помню зачем их сделал... fixed

2023-03-11 12:00 UTC, AlexanderSharygin commented on main-service/src/main/java/ru/practicum/ewm/main_service/compilation/service/CompilationService.java
> +        ResponseEntity<Object> response = statClient.getStats("2000-01-01 00:00:00",
fixed

2023-03-11 12:08 UTC, AlexanderSharygin commented on main-service/src/main/java/ru/practicum/ewm/main_service/compilation/service/CompilationService.java
> +        List<ParticipationRequest> requests = requestRepository
fixed

2023-03-11 12:08 UTC, AlexanderSharygin commented on main-service/src/main/java/ru/practicum/ewm/main_service/compilation/service/CompilationService.java
> +        ResponseEntity<Object> response = statClient.getStats("2000-01-01 00:00:00",
fixed

2023-03-11 12:44 UTC, AlexanderSharygin commented on main-service/src/main/java/ru/practicum/ewm/main_service/location/service/LocationService.java
> +    public Location save(Location location) {
fixed

2023-03-11 15:46 UTC, FanaticFiz approved these changes

2023-03-11 17:40 UTC, merged