Feature comments
AlexanderSharygin/java-explore-with-me-correct pull request #3
Opened 2023-03-13 18:30 UTC by AlexanderSharygin

2023-03-14 18:38 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-03-14 18:38 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/main_service/compilation/controller/CompilationPublicController.java
> +    @GetMapping("/compilations")
А в чем причина этого переноса?

2023-03-14 18:38 UTC, FanaticFiz commented on main-service/src/main/resources/schema.sql
> +    text             VARCHAR(1000)                                   NOT NULL,
`text` это зарезервированное слово в БД. Тип данных есть такой, например.
Да и какой смысл передаёт такое название? Что это за текст такой? Что там лежит?

Нельзя ли подобрать более осмысленное название?

2023-03-14 18:38 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/main_service/event_comment/service/EventCommentsService.java
> +        checkIfEventPublished(event);
`checkIfEventPublished -> throwIfEventPublished`

Просто у check другая специфика, и ждешь от него другого... Это проверка, которая должна вернуть результат. А у тебя именно throw. Вот так и назови...

2023-03-14 18:38 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/main_service/event_comment/service/EventCommentsService.java
> +    public List<EventCommentDto> getAllCommentsByUserId(long userId, Pageable pageable) {
Можно было бы обойтись и без переменной. И в этом методе и в соседних.

```
    public List<EventCommentDto> getAllCommentsByUserId(long userId, Pageable pageable) {
        getUserIfExist(userId);

        return commentRepository.findByUser_Id(userId, pageable).stream()
                                .map(EventCommentMapper::toDtoFromEventComment)
                                .collect(Collectors.toList());
    }
```

2023-03-14 18:38 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/main_service/event_comment/service/EventCommentsService.java
> +            throw new BadRequestException("Admin action could not be empty or null");
Этот BadRequestException ты мог бы и проверить кинуть непосредственно в контроллере. Ну раз это некорректный запрос то это зона ответственности контроллера. 

И в сервисе код будет проще.

2023-03-14 18:38 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/main_service/event_comment/service/EventCommentsService.java
> +                comment.setState(CommentState.APPROVED);
Статики можно было бы заимпортить предварительно

`comment.setState(APPROVED);`

2023-03-15 15:14 UTC, AlexanderSharygin commented on main-service/src/main/java/ru/practicum/ewm/main_service/compilation/controller/CompilationPublicController.java
> +    @GetMapping("/compilations")
мне такой вариант показался удобнее во время отладки. Получилось много контроллеров с разными URL . И когда рядом с методом конnроллера сразу отображается URL - это кажется удобнее

2023-03-15 15:17 UTC, AlexanderSharygin commented on main-service/src/main/java/ru/practicum/ewm/main_service/event_comment/service/EventCommentsService.java
> +        checkIfEventPublished(event);
fixed

2023-03-15 15:22 UTC, AlexanderSharygin commented on main-service/src/main/resources/schema.sql
> +    text             VARCHAR(1000)                                   NOT NULL,
поменял на comment_text

2023-03-15 15:23 UTC, AlexanderSharygin commented on main-service/src/main/java/ru/practicum/ewm/main_service/event_comment/service/EventCommentsService.java
> +            throw new BadRequestException("Admin action could not be empty or null");
fixed

2023-03-15 15:24 UTC, AlexanderSharygin commented on main-service/src/main/java/ru/practicum/ewm/main_service/event_comment/service/EventCommentsService.java
> +                comment.setState(CommentState.APPROVED);
fixed

2023-03-15 15:26 UTC, AlexanderSharygin commented on main-service/src/main/java/ru/practicum/ewm/main_service/event_comment/service/EventCommentsService.java
> +    public List<EventCommentDto> getAllCommentsByUserId(long userId, Pageable pageable) {
fixed

2023-03-21 15:11 UTC, merged